package com.htht.job.core.enums;

public enum DictCodeEnum {
	FINDALlMODELIDENTIFICATION1,
	FINDALLEXECUTIONSTRATEGY1,
	GETUPLOADPATH1,
	GETEXEPATH1,
	FIND_TILE,
	FINDALlMODELIDENTIFICATION,
	FINDALLEXECUTIONSTRATEGY,
	GETUPLOADPATH,
	GETEXEPATH,
	ALGOLOADERPATH,
	SHAREPATH
}


